import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "./globals.css";
import { HeaderWrapper } from "@/components/header/header-wrapper";
import { Toaster } from "@/components/ui/toaster";
import ModalProviders from "@/providers/modal-providers";
import { cn } from "@/lib/utils";
import currentRoute from "@/hooks/current-route";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = currentRoute();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(poppins.className, "bg-slate-50")}>
        {pathname !== "/login" && <HeaderWrapper />}
        <ModalProviders />
        <main className="relative z-[1]">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
